### PR TITLE
resolve conflicts with development

### PR DESCRIPTION
**Pull request by onedebos**

### CODE REVIEW

**Review by JamesOkunlade — CHANGES_REQUESTED** [review]
### Hello @onedebos ,

Good work writing those enumerable methods. However, your code is not passing the test suite and I think it is due to a stray `end` keyword. You'll have to take more time to look into this. You can test each of your methods against an array block to see if they give predicted result before requesting another review. 
- Also, I think your ruby code styling/indentation can be improved. Check the [ruby style guidelines](https://github.com/rubocop-hq/ruby-style-guide) for best practices and how to have consistency in your ruby code.

Please fix those and request for a re-review when you're done. 

Happy coding! :sunglasses:

**Comment by onedebos** [comment]
Fixed linting errors with Rubocop and removed stray end tags.

**Review by JamesOkunlade — CHANGES_REQUESTED** [review]
### Almost there!:slightly_smiling_face::ok_hand: 

- Some of your methods were not named correctly. `my_any`, `my_all`, `my_none` should be `my_none?`, `my_all?`, and `my_none?` respectively. 
- Also, you need to check your `my_count` and `my_inject` methods again as they are not passing the test yet. Work on these again and test there result against corresponding ruby `count` and `inject` methods.
- Lastly, I still think your indentation can be improved. Take for example your `my_all?` method:
```
#bad

def my_all?
    if block_given?
        self.my_each do |i|
            return true if yield(i)
    end
end
    false
end
```
```
#good

def my_all?
    if block_given?
        self.my_each do |i|
            return true if yield(i)
        end
    end
    false
end
```
check the different sections of your code and improve the indentation.

Please make the requested changes and submit for hopefully the last re-review:slightly_smiling_face:
Reach out to me on slack if you any question regarding the changes.

Happy coding:sunglasses:

**Comment by onedebos** [comment]
Hey James,

When I do the 4 space indentation, my code fails stickler and rubocop checks. 

I think the my_count and my_inject methods work now.

**Comment by onedebos** [comment]
my_count method fixed.

**Review by JamesOkunlade — APPROVED** [review]
### All good now!:sunglasses:

It's a:+1: from me. Go ahead and merge.

Good luck with your future projects. 

### P.S
 
Ensure to stick to `git-flow`:slightly_smiling_face:

**Comment by onedebos** [comment]
Thank you, James.

**Pull request merged**
